{
    'name': 'Hospital Management',
    'version': '18.0.2.1.0',
    'author': 'Krishnaprasad K',
    'category': 'Healthcare',
    'summary': 'Complete Hospital Management System',
    'depends': ['base', 'hr', 'mail', 'contacts', 'account', 'sale_management', 'product', 'stock', 'product_expiry', 'pharmacy_stock_notification'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'data/kerala_state.xml',
        'views/hospital_views.xml',
        'views/patient_views.xml',
        'views/prescription_views.xml',
        'views/pharmacy_views.xml',
        'views/product_views.xml',
        'views/medicine_brand.xml',
        'views/medicine_product_views.xml',
        'views/procedure_product_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_clinic_form.xml',
        'views/account_move.xml',
        'views/consultation_payment_view.xml',
        'views/medicine_purchase_wizard_views.xml',
        'views/stock_lot_view.xml',
        'views/res_config_settings_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
             'hospital_management/static/src/css/prescription.css',
             'hospital_management/static/src/scss/clinic.scss',
             'hospital_management/static/src/js/dose_select_focus.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}