from . import op_ticket
from . import patient
from . import prescription_line
from . import medicine_brand
from . import hospital_pharmacy
from . import dose_preset
from . import product_template
from . import account_move
from . import sale_order
from . import op_procedure_line
from . import product_product
from . import stock_lot
from . import stock_move
from . import sale_order_line
from . import res_config_settings
from . import res_partner
